# https://travis-ci.org/jazzband/django-oauth-toolkit
dist: xenial

language: python

python:
  - "3.7"

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

install:
  - pip install coveralls tox tox-travis

script:
  - rm -r $TRAVIS_BUILD_DIR/.tox
  - tox -op auto

after_script:
  - coveralls
